/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import java.nio.file.Paths;

import static java.nio.file.Paths.*;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void testLinterMethod() {
        App test = new App();

        App.readJSfile(get("./resources/gates.js"));
//        assertTrue(true, App.readJSfile(get("./resources/gates.js")));
    }
}
