/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;



public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
//        System.out.println(new App().getGreeting());
        readJSfile(Paths.get("./resources/gates.js"));

    }
    public static void readJSfile (Path path){
        int lineNumber = 0;
        try {
            Scanner gatesScanner = new Scanner(new File("resources/gates.js"));
            while(gatesScanner.hasNextLine()){
                lineNumber++;
                String line = gatesScanner.nextLine();
                if(line.length() > 0 ) {
                    if (!line.endsWith(";") && !line.endsWith("{") && !line.endsWith("}") && !line.isEmpty() && !line.contains("else") && !line.contains("if")) {
                        System.out.println("Line " + lineNumber + " Missing semicolon.");
                    }
                }
            }

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }

    }

}
