/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Scanner;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRollingDiceMethod(){
        int roll  = 4;
        int [] actual = Library.roll(4);
        assertEquals(actual.length,roll);
    }

    @Test public void testContainsDuplicateMethod(){
        int[] array = {1,2,3,4,5,6,7};
        int[] array2 = {31, 28, 31, 30, 31, 30,
                31, 31, 30, 31, 30, 31};
        boolean actual = Library.containsDuplicates(array);
        boolean actual2 = Library.containsDuplicates(array2);
        assertEquals(actual,false);
        assertEquals(actual2,true);
    }

    @Test public void testCalculatingAverageMethod(){
        double expected = 19.0;
        int[] array = {2,5,8,12,51,25,30};
        float actual = Library.calcAverage(array);
        System.out.println(actual);
        assertEquals(actual, expected,5*Math.ulp(expected));
    }

    @Test public void testCalcAoA(){
        int[][] arrayOfArrays1 = {
                {42, 50, 47, 31, 58, 60, 40},
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[][] arrayOfArrays2 = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {42, 50, 47, 31, 58, 60, 40},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[][] arrayOfArrays3 = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {42, 50, 47, 31, 58, 60, 40},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] expected = new int[] {42, 50, 47, 31, 58, 60, 40};
        int[] actual1 = Library.calcAoA(arrayOfArrays1);
        int[] actual2 = Library.calcAoA(arrayOfArrays2);
        int[] actual3 = Library.calcAoA(arrayOfArrays3);
        assertArrayEquals(actual1, expected);
        assertArrayEquals(actual2, expected);
        assertArrayEquals(actual3, expected);
    }

    @Test public void testMaps(){
        int [][] data = {{1,2}, {3,7,8}};
        assertEquals("should find that 4, 5 and 6 are missing", "High: 8\nLow: 1\nNever saw temperature : 4\nNever saw temperature : 5\nNever saw temperature : 6\n", Library.analyzeWeatherData(data));
    }

    @Test public void testMapLongArray(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String expected = new String("High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature : 63\n" +
                "Never saw temperature : 67\n" +
                "Never saw temperature : 68\n" +
                "Never saw temperature : 69\n");
        assertEquals(expected, Library.analyzeWeatherData((weeklyMonthTemperatures)));
    }

    @Test public void tallyTest(){
        ArrayList<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        String result = "Bush";
        assertEquals(result, Library.tally(votes));
    }


}
