/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

    @Test public void testRollingDiceMethod(){
        int roll  = 4;
        int [] actual = Library.roll(4);
        assertEquals(actual.length,roll);
    }

    @Test public void testContainsDuplicateMethod(){
        int[] array = {1,2,3,4,5,6,7};
        int[] array2 = {31, 28, 31, 30, 31, 30,
                31, 31, 30, 31, 30, 31};
        boolean actual = Library.containsDuplicates(array);
        boolean actual2 = Library.containsDuplicates(array2);
        assertEquals(actual,false);
        assertEquals(actual2,true);
    }

    @Test public void testCalculatingAverageMethod(){
        double expected = 19.0;
        int[] array = {2,5,8,12,51,25,30};
        float actual = Library.calcAverage(array);
        System.out.println(actual);
        assertEquals(actual, expected,5*Math.ulp(expected));
    }

    @Test public void testCalcAoA(){
        int[][] arrayOfArrays1 = {
                {42, 50, 47, 31, 58, 60, 40},
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[][] arrayOfArrays2 = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {42, 50, 47, 31, 58, 60, 40},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[][] arrayOfArrays3 = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {42, 50, 47, 31, 58, 60, 40},
                {65, 56, 55, 52, 55, 62, 57}
        };
        int[] expected = new int[] {42, 50, 47, 31, 58, 60, 40};
        int[] actual1 = Library.calcAoA(arrayOfArrays1);
        int[] actual2 = Library.calcAoA(arrayOfArrays2);
        int[] actual3 = Library.calcAoA(arrayOfArrays3);
        assertArrayEquals(actual1, expected);
        assertArrayEquals(actual2, expected);
        assertArrayEquals(actual3, expected);
    }
}
