/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;


public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("Rolling Dice");
        roll(4);
        System.out.println("-----------------------------");

        System.out.println("Contains Duplicate");
        int[] array = {31, 28, 31, 30, 31, 30,
                31, 31, 30, 31, 30, 31};
        int[] array2 = {1,2,3,4,5,6,7};
        System.out.println(containsDuplicates(array));
        System.out.println(containsDuplicates(array2));
        System.out.println("-----------------------------");


        System.out.println("Calculating Average");
        int[] array3 = {2,5,8,12,51,25};
        System.out.println(calcAverage(array3));
        System.out.println("double : " + String.format("%.2f", calcAverage(array3)));
        System.out.println("-----------------------------");


        System.out.println("Array of Arrays");
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {42, 50, 47, 31, 58, 60, 40},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        System.out.println(Arrays.toString(calcAoA(weeklyMonthTemperatures)));

        System.out.println("-----------------------------");

        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
//        analyzeWeatherData(weeklyMonthTemperatures);
        System.out.println(analyzeWeatherData(weeklyMonthTemperatures));

        System.out.println("-----------------------------");

        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        System.out.println(tally(votes));


    }

    public static int[] roll(int n){
        int [] valArr = new int[n];
        for(int i = 0; i < n; i++){
            valArr[i] = (int)Math.ceil(Math.random() * 6);
        }
        System.out.println(Arrays.toString(valArr));
        return (int[]) valArr;
    }

    public static boolean containsDuplicates(int[] arr){
        for(int i = 0; i < arr.length; i++){
            int temp = arr[i];
            for(int j = i+1; j < arr.length; j++){
                if(temp == arr[j]) return true;
            }
        }
        return false;
    }

    public static float calcAverage (int[] arr){
        int val = 0;
        for(int i : arr){
            val += i;
        }

        return (float) val/arr.length;
    }

    public static int[] calcAoA(int [][] arr){
        int [] newArr = new int [arr[0].length];
        float lowestAvg = calcAverage(arr[0]);
        for(int[] i : arr){
            if(calcAverage(i) <= lowestAvg){
//                System.out.println(Arrays.toString(i));
                lowestAvg = calcAverage(i);
                newArr = i;
            }
        }
        return newArr;
    }

    public static String analyzeWeatherData(int [] [] aOa){
        HashSet<Integer> temp = new HashSet<>();
        int min = 120;
        int max = 0;
        String notSawStr = "";
        for(int [] arr : aOa){
            for(int i : arr){
                temp.add(i);
                if(i > max) max = i;
                else if (i < min) min = i;
            }
        }
        for(int i = min; i < max; i++){
            if(!temp.contains(i)){
                notSawStr += "Never saw temperature : " + i +"\n";

            }
        }
        return String.format("High:%d \nLow: %d \n%s", max, min, notSawStr);
    }

    public static String tally(List<String> list){
        String winner = "";
        int voteCount = 0;
        HashMap<String, Integer> timesVoted = new HashMap<>();

        //put the names into the hashmap
        for (String j : list){
            timesVoted.put(j,0);
        }

        for(String i : list){
            if(timesVoted.get(i) > voteCount) {
                voteCount = timesVoted.get(i) +1;
                winner = i;
            }else timesVoted.put(i, timesVoted.get(i) + 1);
        }

        return winner;
    }




}
